In [1]:
import pandas as pd

import os
working_directory = os.getcwd()
print(working_directory)

/Users/elizabeth

In [45]:
path = working_directory + '/Downloads/dc_marvel_movie_performance.csv'
movie_performance = pd.read_csv(path , encoding='latin1', sep=";")
movie_performance.head()

,Film,U.S. release date,Box office gross Domestic (U.S. and Canada ),Box office gross Other territories,Box office gross Worldwide,Budget,MCU,Phase,Distributor,MPAA Rating,...,Character Family,Domestic %,Gross to Budget,Rotten Tomatoes Critic Score,Male/Female-led,Year,Inflation Adjusted Worldwide Gross,Inflation Adjusted Budget,2.5x prod,Break Even
0,Superman,15/12/1978,"$134,478,449","$166,000,000","$300,478,449","$55,000,000",False,NaN,Warner Bros.,PG,...,Superman,45%,5.46,94,Male,1978,"$1,404,237,104","$257,033,544","$137,500,000",Success
1,Superman II,19/06/1981,"$108,185,706","$108,200,000","$216,385,706","$54,000,000",False,NaN,Warner Bros.,PG,...,Superman,50%,4.01,83,Male,1981,"$725,336,273","$181,010,842","$135,000,000",Success
2,Superman III,17/06/1983,"$59,950,623","$20,300,000","$80,250,623","$39,000,000",False,NaN,Warner Bros.,PG,...,Superman,75%,2.06,29,Male,1983,"$245,506,947","$119,310,861","$97,500,000",Flop
3,Supergirl,21/11/1984,"$14,296,438",NaN,"$14,296,438","$35,000,000",False,NaN,Tri-Star Pictures,PG,...,Superman,100%,0.41,8,Female,1984,"$41,926,345","$102,642,497","$87,500,000",Flop
4,Howard the Duck,08/01/1986,"$16,295,774","$21,667,000","$37,962,774","$37,000,000",False,NaN,Universal Pictures,PG,...,Howard the Duck,43%,1.03,13,Male,1986,"$37,962,774","$37,000,000","$92,500,000",Flop

In [47]:
print(movie_performance.columns)

Index(['Film', 'U.S. release date',
       'Box office gross Domestic (U.S. and Canada )',
       'Box office gross Other territories', 'Box office gross Worldwide',
       'Budget', 'MCU', 'Phase', 'Distributor', 'MPAA Rating', 'Length',
       'Minutes', 'Franchise', 'Character Family', 'Domestic %',
       'Gross to Budget', 'Rotten Tomatoes Critic Score', 'Male/Female-led',
       'Year', 'Inflation Adjusted Worldwide Gross',
       'Inflation Adjusted Budget', '2.5x prod', 'Break Even'],
      dtype='object')

In [49]:
# Check if the columns exist 
columns_to_remove = ['MCU', 'Phase', 'Franchise']
missing_columns = [col for col in columns_to_remove if col not in movie_performance.columns]
if missing_columns:
    print(f"Columns {missing_columns} not found in the DataFrame.")
else:
    # Remove the specified columns
    movie_performance = movie_performance.drop(columns=columns_to_remove)

    # Display the updated DataFrame after removing columns
    print("\nDataFrame after removing columns:")
    print(movie_performance.head())

DataFrame after removing columns:
              Film U.S. release date  \
0         Superman        15/12/1978
1      Superman II        19/06/1981
2     Superman III        17/06/1983
3        Supergirl        21/11/1984
4  Howard the Duck        08/01/1986

  Box office gross Domestic (U.S. and Canada )  \
0                                $134,478,449
1                                $108,185,706
2                                 $59,950,623
3                                 $14,296,438
4                                 $16,295,774

  Box office gross Other territories Box office gross Worldwide        Budget  \
0                      $166,000,000               $300,478,449   $55,000,000
1                      $108,200,000               $216,385,706   $54,000,000
2                       $20,300,000                $80,250,623   $39,000,000
3                                NaN               $14,296,438   $35,000,000
4                       $21,667,000                $37,962,774   $37,000,000

          Distributor MPAA Rating    Length  Minutes Character Family  \
0        Warner Bros.          PG  02:23:00      143         Superman
1        Warner Bros.          PG  02:07:00      127         Superman
2        Warner Bros.          PG  02:05:00      125         Superman
3   Tri-Star Pictures          PG  02:04:00      124         Superman
4  Universal Pictures          PG  01:50:00      110  Howard the Duck

  Domestic %  Gross to Budget  Rotten Tomatoes Critic Score Male/Female-led  \
0        45%             5.46                            94            Male
1        50%             4.01                            83            Male
2        75%             2.06                            29            Male
3       100%             0.41                             8          Female
4        43%             1.03                            13            Male

   Year Inflation Adjusted Worldwide Gross Inflation Adjusted Budget  \
0  1978                    $1,404,237,104              $257,033,544
1  1981                      $725,336,273              $181,010,842
2  1983                      $245,506,947              $119,310,861
3  1984                       $41,926,345              $102,642,497
4  1986                       $37,962,774               $37,000,000

       2.5x prod Break Even
0  $137,500,000     Success
1  $135,000,000     Success
2   $97,500,000        Flop
3   $87,500,000        Flop
4   $92,500,000        Flop

In [50]:
print(movie_performance.columns)

Index(['Film', 'U.S. release date',
       'Box office gross Domestic (U.S. and Canada )',
       'Box office gross Other territories', 'Box office gross Worldwide',
       'Budget', 'Distributor', 'MPAA Rating', 'Length', 'Minutes',
       'Character Family', 'Domestic %', 'Gross to Budget',
       'Rotten Tomatoes Critic Score', 'Male/Female-led', 'Year',
       'Inflation Adjusted Worldwide Gross', 'Inflation Adjusted Budget',
       '2.5x prod', 'Break Even'],
      dtype='object')

In [51]:
# Get unique values of the "Character Family" column. Not sure what unique is, so going as per google suggestion = alphabetically
unique_values = sorted(movie_performance['Character Family'].unique())

# Print unique values alphabetically
print("Unique values of 'Character Family' column sorted from A to Z:")
for value in unique_values:
    print(value)

Unique values of 'Character Family' column sorted from A to Z:
Ant-Man
Aquaman
Avengers
Batman
Birds of Prey
Black Panther
Black Widow
Blade
Blue Beetle
Captain America
Captain Marvel
Constantine
Daredevil
Doctor Strange
Eternals
Fantastic Four
Flash
Ghost Rider
Green Lantern
Guardians of the Galaxy
Howard the Duck
Hulk
Iron Man
Jonah Hex
Justice League
Punisher
Shang-Chi
Shazam
Spider-Man
Spider-Man Allies and Villains
Suicide Squad
Superman
Swamp Thing
Teen Titans
Thor
Watchmen
Wonder Woman
X-Men

In [54]:
#Longest movie time
# Find the index of the row with the Length of the films 
max_time_index = movie_performance['Length'].idxmax()

# Get the details of the longest movie
longest_movie = movie_performance.loc[max_time_index]

# Print the details of the longest movie
print("Longest Movie:")
print(longest_movie)

Longest Movie:
Film                                                              Avengers: Endgame
U.S. release date                                                        26/04/2019
Box office gross Domestic (U.S. and Canada )                          $858,373,000
Box office gross Other territories                                  $1,941,066,100
Box office gross Worldwide                                          $2,799,439,100
Budget                                                                $356,000,000
Distributor                                     Walt Disney Studios Motion Pictures
MPAA Rating                                                                   PG-13
Length                                                                     03:01:00
Minutes                                                                         181
Character Family                                                           Avengers
Domestic %                                                                      31%
Gross to Budget                                                                7.86
Rotten Tomatoes Critic Score                                                     94
Male/Female-led                                                                Male
Year                                                                           2019
Inflation Adjusted Worldwide Gross                                  $2,799,439,100
Inflation Adjusted Budget                                             $356,000,000
2.5x prod                                                             $890,000,000
Break Even                                                                  Success
Name: 84, dtype: object

In [55]:
# Group the DataFrame by the "Break Even" column and calculate the mean of "Rotten Tomatoes Critic Score" for each group
mean_scores = movie_performance.groupby('Break Even')['Rotten Tomatoes Critic Score'].mean()

# Print the mean scores
print("Mean values of 'Rotten Tomatoes Critic Score' per 'Break Even' category:")
print(mean_scores)

Mean values of 'Rotten Tomatoes Critic Score' per 'Break Even' category:
Break Even
Flop       42.361702
Success    76.727273
Name: Rotten Tomatoes Critic Score, dtype: float64

In [57]:
# Define the bins and labels for the recommended categories
bins = [-float('inf'), 39, 59, 89, float('inf')]
labels = ['Strongly No', 'No', 'Yes', 'Strongly Yes']

# Add a new column "Recommended" based on the "Rotten Tomatoes Critic Score"
movie_performance['Recommended'] = pd.cut(movie_performance['Rotten Tomatoes Critic Score'], bins=bins, labels=labels)

# Print the DataFrame to show the new column
print(movie_performance.head())

              Film U.S. release date  \
0         Superman        15/12/1978
1      Superman II        19/06/1981
2     Superman III        17/06/1983
3        Supergirl        21/11/1984
4  Howard the Duck        08/01/1986

  Box office gross Domestic (U.S. and Canada )  \
0                                $134,478,449
1                                $108,185,706
2                                 $59,950,623
3                                 $14,296,438
4                                 $16,295,774

  Box office gross Other territories Box office gross Worldwide        Budget  \
0                      $166,000,000               $300,478,449   $55,000,000
1                      $108,200,000               $216,385,706   $54,000,000
2                       $20,300,000                $80,250,623   $39,000,000
3                                NaN               $14,296,438   $35,000,000
4                       $21,667,000                $37,962,774   $37,000,000

          Distributor MPAA Rating    Length  Minutes  ... Domestic %  \
0        Warner Bros.          PG  02:23:00      143  ...        45%
1        Warner Bros.          PG  02:07:00      127  ...        50%
2        Warner Bros.          PG  02:05:00      125  ...        75%
3   Tri-Star Pictures          PG  02:04:00      124  ...       100%
4  Universal Pictures          PG  01:50:00      110  ...        43%

  Gross to Budget  Rotten Tomatoes Critic Score  Male/Female-led  Year  \
0            5.46                            94             Male  1978
1            4.01                            83             Male  1981
2            2.06                            29             Male  1983
3            0.41                             8           Female  1984
4            1.03                            13             Male  1986

   Inflation Adjusted Worldwide Gross Inflation Adjusted Budget  \
0                     $1,404,237,104              $257,033,544
1                       $725,336,273              $181,010,842
2                       $245,506,947              $119,310,861
3                        $41,926,345              $102,642,497
4                        $37,962,774               $37,000,000

       2.5x prod Break Even   Recommended
0  $137,500,000     Success  Strongly Yes
1  $135,000,000     Success           Yes
2   $97,500,000        Flop   Strongly No
3   $87,500,000        Flop   Strongly No
4   $92,500,000        Flop   Strongly No

[5 rows x 21 columns]

In [76]:
# Define the bins and labels for the recommended categories
bins = [-float('inf'), 39, 59, 89, float('inf')]
labels = ['Strongly No', 'No', 'Yes', 'Strongly Yes']

# Add a new column "Recommended" based on the "Rotten Tomatoes Critic Score"
movie_performance['Recommended'] = pd.cut(movie_performance['Rotten Tomatoes Critic Score'], bins=bins, labels=labels)

# Calculate the percentage of films falling into each recommend category
percentage = movie_performance['Recommended'].value_counts(normalize=True) * 100

# Print the percentage of films falling into recommend category
print("Percentage of films falling into each recommended category:")
print(percentage)

Percentage of films falling into each recommended category:
Recommended
Yes             38.938053
Strongly No     26.548673
Strongly Yes    21.238938
No              13.274336
Name: proportion, dtype: float64

In [59]:
# Group the data by "Character Family" and count the number of "Flops" and "Successes"
success_rate = movie_performance.groupby('Character Family')['Break Even'].value_counts().unstack().fillna(0)

# Calculate the success rate
success_rate['Success Rate'] = (success_rate['Success'] / (success_rate['Success'] + success_rate['Flop'])) * 100

# Rename the columns
success_rate = success_rate.rename(columns={'Flop': 'Number of Flops', 'Success': 'Number of Successes'})

# Reorder the columns
success_rate = success_rate[['Number of Flops', 'Number of Successes', 'Success Rate']]

# Print the success_rate DataFrame
print(success_rate)

Break Even                      Number of Flops  Number of Successes  \
Character Family
Ant-Man                                     1.0                  2.0
Aquaman                                     1.0                  1.0
Avengers                                    0.0                  4.0
Batman                                      3.0                  9.0
Birds of Prey                               1.0                  0.0
Black Panther                               0.0                  2.0
Black Widow                                 1.0                  0.0
Blade                                       1.0                  2.0
Blue Beetle                                 1.0                  0.0
Captain America                             0.0                  3.0
Captain Marvel                              1.0                  1.0
Constantine                                 1.0                  0.0
Daredevil                                   2.0                  0.0
Doctor Strange                              0.0                  2.0
Eternals                                    1.0                  0.0
Fantastic Four                              2.0                  1.0
Flash                                       1.0                  0.0
Ghost Rider                                 2.0                  0.0
Green Lantern                               1.0                  0.0
Guardians of the Galaxy                     0.0                  3.0
Howard the Duck                             1.0                  0.0
Hulk                                        2.0                  0.0
Iron Man                                    0.0                  3.0
Jonah Hex                                   1.0                  0.0
Justice League                              2.0                  1.0
Punisher                                    2.0                  1.0
Shang-Chi                                   1.0                  0.0
Shazam                                      2.0                  1.0
Spider-Man                                  0.0                 10.0
Spider-Man Allies and Villains              2.0                  2.0
Suicide Squad                               1.0                  1.0
Superman                                    5.0                  3.0
Swamp Thing                                 1.0                  0.0
Teen Titans                                 0.0                  1.0
Thor                                        0.0                  4.0
Watchmen                                    1.0                  0.0
Wonder Woman                                1.0                  1.0
X-Men                                       5.0                  8.0

Break Even                      Success Rate
Character Family
Ant-Man                            66.666667
Aquaman                            50.000000
Avengers                          100.000000
Batman                             75.000000
Birds of Prey                       0.000000
Black Panther                     100.000000
Black Widow                         0.000000
Blade                              66.666667
Blue Beetle                         0.000000
Captain America                   100.000000
Captain Marvel                     50.000000
Constantine                         0.000000
Daredevil                           0.000000
Doctor Strange                    100.000000
Eternals                            0.000000
Fantastic Four                     33.333333
Flash                               0.000000
Ghost Rider                         0.000000
Green Lantern                       0.000000
Guardians of the Galaxy           100.000000
Howard the Duck                     0.000000
Hulk                                0.000000
Iron Man                          100.000000
Jonah Hex                           0.000000
Justice League                     33.333333
Punisher                           33.333333
Shang-Chi                           0.000000
Shazam                             33.333333
Spider-Man                        100.000000
Spider-Man Allies and Villains     50.000000
Suicide Squad                      50.000000
Superman                           37.500000
Swamp Thing                         0.000000
Teen Titans                       100.000000
Thor                              100.000000
Watchmen                            0.000000
Wonder Woman                       50.000000
X-Men                              61.538462

In [67]:
path = working_directory + '/Downloads/directors.csv'
directors = pd.read_csv(path , encoding='latin1', sep=";")
print(directors)

                              Movie         Director
0                      Man of Steel      Zack Snyder
1                             Steel  Kenneth Johnson
2                          Superman   Richard Donner
3                      Superman III   Richard Lester
4                       Superman II   Richard Lester
5                         Supergirl   Jeannot Szwarc
6  Superman IV: The Quest for Peace  Sidney J. Furie
7                  Superman Returns     Bryan Singer
8                      Wonder Woman    Patty Jenkins
9                 Wonder Woman 1984    Patty Jenkins

In [74]:
# Perform inner join on film title to get rows with films present in both DataFrames
joined_data = pd.merge(movie_performance, directors, left_on='Film', right_on='Movie', how='inner')

# Print the result
print(joined_data)

                               Film U.S. release date  \
0                          Superman        15/12/1978
1                       Superman II        19/06/1981
2                      Superman III        17/06/1983
3                         Supergirl        21/11/1984
4  Superman IV: The Quest for Peace        24/07/1987
5                             Steel        15/08/1997
6                  Superman Returns        28/06/2006
7                      Man of Steel        14/06/2013
8                      Wonder Woman        06/02/2017
9                 Wonder Woman 1984        25/12/2020

  Box office gross Domestic (U.S. and Canada )  \
0                                $134,478,449
1                                $108,185,706
2                                 $59,950,623
3                                 $14,296,438
4                                 $15,681,020
5                                  $1,710,972
6                                $200,081,192
7                                $291,045,518
8                                $412,845,172
9                                 $46,801,036

  Box office gross Other territories Box office gross Worldwide  \
0                      $166,000,000               $300,478,449
1                      $108,200,000               $216,385,706
2                       $20,300,000                $80,250,623
3                                NaN               $14,296,438
4                       $14,600,000                $30,281,020
5                           $91,000                 $1,801,972
6                      $191,000,000               $391,081,192
7                      $379,100,000               $670,145,518
8                      $411,125,510               $823,970,682
9                      $122,800,000               $169,601,036

          Budget        Distributor MPAA Rating    Length  Minutes  ...  \
0   $55,000,000        Warner Bros.          PG  02:23:00      143  ...
1   $54,000,000        Warner Bros.          PG  02:07:00      127  ...
2   $39,000,000        Warner Bros.          PG  02:05:00      125  ...
3   $35,000,000   Tri-Star Pictures          PG  02:04:00      124  ...
4   $17,000,000        Warner Bros.          PG  01:30:00       90  ...
5   $16,000,000        Warner Bros.       PG-13  01:37:00       97  ...
6  $270,000,000        Warner Bros.       PG-13  02:34:00      154  ...
7  $225,000,000        Warner Bros.       PG-13  02:23:00      143  ...
8  $149,000,000        Warner Bros.       PG-13  02:21:00      141  ...
9  $200,000,000        Warner Bros.       PG-13  02:31:00      151  ...

  Rotten Tomatoes Critic Score Male/Female-led  Year  \
0                           94            Male  1978
1                           83            Male  1981
2                           29            Male  1983
3                            8          Female  1984
4                           10            Male  1987
5                           12            Male  1997
6                           74            Male  2006
7                           56            Male  2013
8                           93          Female  2017
9                           58          Female  2020

   Inflation Adjusted Worldwide Gross Inflation Adjusted Budget  \
0                     $1,404,237,104              $257,033,544
1                       $725,336,273              $181,010,842
2                       $245,506,947              $119,310,861
3                        $41,926,345              $102,642,497
4                        $81,220,728               $45,597,948
5                         $3,420,958               $30,375,236
6                       $591,086,599              $408,082,478
7                       $876,532,581              $294,294,038
8                     $1,024,254,126              $185,217,591
9                       $199,673,523              $235,462,622

       2.5x prod Break Even   Recommended                             Movie  \
0  $137,500,000     Success  Strongly Yes                          Superman
1  $135,000,000     Success           Yes                       Superman II
2   $97,500,000        Flop   Strongly No                      Superman III
3   $87,500,000        Flop   Strongly No                         Supergirl
4   $42,500,000        Flop   Strongly No  Superman IV: The Quest for Peace
5   $40,000,000        Flop   Strongly No                             Steel
6  $675,000,000        Flop           Yes                  Superman Returns
7  $562,500,000     Success            No                      Man of Steel
8  $372,500,000     Success  Strongly Yes                      Wonder Woman
9  $500,000,000        Flop            No                 Wonder Woman 1984

          Director
0   Richard Donner
1   Richard Lester
2   Richard Lester
3   Jeannot Szwarc
4  Sidney J. Furie
5  Kenneth Johnson
6     Bryan Singer
7      Zack Snyder
8    Patty Jenkins
9    Patty Jenkins

[10 rows x 23 columns]